Update metadata into main (#68)
* Update metadata (#44)

Original design discussion PR: https://github.com/metaplex-foundation/metaplex-program-library/pull/1121

Original merged PR: https://github.com/metaplex-foundation/mpl-bubblegum/pull/3

---------

* fix protocol conflicts

* allow updating creators without new verifications

* cleanup

* conflicts

* conflicts

* all tests included

* regen solita and fix bugs

* small fixes

* nit

* address code review, without additional test

* added creator verification test

* Regenerate js client

* Rename old_metadata to current_metadata

* Use UpdateArgs to group new metadata params

* Prevent existing verified creators from being removed

Exception: allow verification/unverification during metadata
update for the signer of the tx.

* Derive Default on UpdateArgs

* Fix typo

* Regenerate IDL, Rust client and Umi client

* Regenerate js-solita

* Add canopy to JS Solita test since it uses 2 nodes

* Run CI on any PR

* Removing SetDecompressableState from pub enum InstructionName

* Remove `update_metadata_collection_nft` instruction (#47)

* Remove update_metadata_collection_nft ix

* Remove unneeded checks and errors

* Regenerate IDL and clients

* Update Solita test

---------

Co-authored-by: Sam Orend <sam.orend22@gmail.com>

* Avoid inlining UpdateArgs (#50)

* Adding LeafSchemaEvent struct to Rust client

* Add leaf schema accessors to program and Rust client

* Add InstructionName::UpdateMetadata to Rust client

* chore: Release mpl-bubblegum version 1.0.1-beta.1

* Add borsh version range (#54)

* Add borsh version range

* Update lock file

* chore: Release mpl-bubblegum version 1.0.1-beta.2

* Remove optional metadata buffer account from update_metadata

* Update Rust and Umi JS clients, update IDL

* Update js-solita client

* Fixing rust client cargo lock after release downgrades it

* chore: Release mpl-bubblegum version 1.0.1-beta.3

* Delete and regenerate rust client Cargo.lock after release downgrades borsh 0.10.3

* Add update_metadata_collection_nft

* Regenerate clients

* Regenerate Solita JS client

* update Solita tests

* Fix path to js test script

* Remove signer req for tree delegate on update_metadata_collection_nft

* Regenerate Solita JS client

* Add tests for using correct ix based on if item is in collection

* Combine update_metadata and update_metadata_collection_nft

* Regenerate JS and Rust clients

* Regenerate Solita JS client

* Update Solita tests

* Removed unneeded instruction name

* Regenerate IDL

* Clean up README and add update_metadata

* Add updateArgs and fix links

* Remove redundancies and clarify

* chore: Release mpl-bubblegum version 1.0.1-beta.4

---------

Co-authored-by: Sam Orend <sam.orend22@gmail.com>
Co-authored-by: Fernando Otero <febo@metaplex.com>
Co-authored-by: febo <febo@users.noreply.github.com>
Co-authored-by: danenbm <danenbm@users.noreply.github.com>